#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
colorscheme = "codedark"
colorscheme_bg = "dark"
enable_guicolors = true
statusline_separator = "arrow"
statusline_iseparator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
filetree_direction = "right"
filemanager = "nerdtree"
autocomplete_method = "coc"

[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "cycle"
auto_completion_complete_with_key_sequence = "nil"
auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
name = "lang#python"
python_file_head = []

[[layers]]
name = "lang#rust"

[[layers]]
name = "lsp"
filetypes = [
  "rust"
]
[layers.override_cmd]
rust = ["rls"]

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#haskell"

[[layers]]
name = "lang#assembly"

[[layers]]
name = "colorscheme"

[[layers]]
name = "lang#scala"

[[layers]]
name = "lang#kotlin"


[[custom_plugins]]
repo = "liuchengxu/space-vim-dark"
merged = 0

[[custom_plugins]]
repo = "shime/vim-livedown"


[[custom_plugins]]
repo = "airblade/vim-gitgutter"

[[custom_plugins]]
repo = "tpope/vim-fugitive"

[[custom_plugins]]
repo = "cometsong/CommentFrame.vim"

[[custom_plugins]]
repo = "voldikss/vim-floaterm"

[[custom_plugins]]
repo = "vimwiki/vimwiki"

[[custom_plugins]]
repo = "wfxr/minimap.vim"

[[custom_plugins]]
repo = "Shougo/vimproc.vim"

[[custom_plugins]]
repo = "dracula/vim"

[[custom_plugins]]
repo = "tomasiser/vim-code-dark"

[[custom_plugins]]
repo = "ledesmablt/vim-run"

[[custom_plugins]]
repo = "metakirby5/codi.vim"

[[custom_plugins]]
repo = "preservim/nerdcommenter"

[[custom_plugins]]
repo = "tpope/vim-surround"

[[custom_plugins]]
repo = "tpope/vim-eunuch"

[[custom_plugins]]
repo = "junegunn/goyo.vim"

[[layers]]
  name = "lang#sh"

[[custom_plugins]]
repo = "mattn/emmet-vim"

[[custom_plugins]]
repo = "sainnhe/gruvbox-material"

[[custom_plugins]]
repo = "easymotion/vim-easymotion"

[[custom_plugins]]
repo = "alvan/vim-closetag"

[[custom_plugins]]
repo = "neovimhaskell/haskell-vim"

[[custom_plugins]]
repo = "johannesthyssen/vim-signit"

[[layers]]
name = "shell"
default_position = "bottom"
default_height = 30

[[layers]]
name = "lang#go"

[[layers]]
name = "format"

[[custom_plugins]]
repo = "lilydjwg/colorizer"
merged = false
