[line_break]
disabled = true

[aws]
disabled = true

[rust]
disabled = true

[elixir]
disabled = true

[scala]
disabled = true

[character]
success_symbol = '[λ](bold yellow)'
error_symbol = '[λ](bold red)'

[python]
python_binary = "python3"

